version = "1.0"

[main]
name = "Pluto.jl"

[main.runtime]
name = "Runtime"

[main.runtime.public_url]
type = "text"
ask = "Public URL"
readonly = true
bind = "null"

[main.runtime.internal_port]
type = "number"
ask = "Internal port"
readonly = true
bind = "null"

[main.runtime.notebooks_dir]
type = "text"
ask = "Notebooks directory"
readonly = true
bind = "null"

[main.actions]
name = "Package actions"

[main.actions.update_environment]
type = "button"
ask = "Update Julia environment"
style = "info"
icon = "flask"
bind = "null"
