version = "1.0"

[main]
name = "Pluto.jl"

[main.public_url]
type = "text"
ask = "Public URL"
readonly = true
bind = "null"

[main.internal_port]
type = "text"
ask = "Internal port"
readonly = true
bind = "null"

[main.notebooks_dir]
type = "text"
ask = "Notebooks directory"
readonly = true
bind = "null"
