#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

if [ -d "$install_dir" ]; then
  ynh_backup "$install_dir"
fi

if [ -d "$data_dir" ]; then
  ynh_backup "$data_dir"
fi

if [ -d "$depot_dir" ]; then
  ynh_backup "$depot_dir"
fi
