#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

_ensure_julia_available

port="$(ynh_app_setting_get --app="$app" --key=port)"
ynh_app_setting_set --app="$app" --key=depot_dir --value="$depot_dir"

mkdir -p "$install_dir" "$data_dir" "$depot_dir"
chown -R "$app:$app" "$install_dir" "$data_dir" "$depot_dir"

_pluto_install_deps

run_script="$install_dir/run"
cp "$YNH_APP_BASEDIR/conf/run.sh" "$run_script"
_replace_in_file "__JULIA_BIN__" "$julia_bin" "$run_script"
_replace_in_file "__INSTALL_DIR__" "$install_dir" "$run_script"
_replace_in_file "__PORT__" "$port" "$run_script"
chmod 755 "$run_script"
chown "$app:$app" "$run_script"

ynh_config_add_nginx

systemd_conf="$YNH_APP_BASEDIR/conf/systemd.service"
_replace_in_file "__PORT__" "$port" "$systemd_conf"
_replace_in_file "__JULIA_BIN__" "$julia_bin" "$systemd_conf"
_replace_in_file "__INSTALL_DIR__" "$install_dir" "$systemd_conf"
_replace_in_file "__DATA_DIR__" "$data_dir" "$systemd_conf"
_replace_in_file "__DEPOT_DIR__" "$depot_dir" "$systemd_conf"
_replace_in_file "__APP_HOME__" "$app_home" "$systemd_conf"
ynh_config_add_systemd

ynh_systemctl --service="$app" --action="start"
